--USING THE ALTER COMMAND IN HERE 
--TO DISPLAY ALL THE CONSTRAINT WE CAN USE THE 'USER_CONSTRAINTS' TABLE AS 
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME='PRODUCT'
--CHECKING THE TABLE STRUCTURE
DESCRIBE PRODUCT
--HERE USING THE ALTER COMMAND WE CAN CHANGE THE DATAT TYPE SIZE OF THE FIELD IN ORACLE SQL 
ALTER TABLE PRODUCT MODIFY PRODUCT_NAME VARCHAR2(100)
--WE CAN CHANGE THE NOT NULL CONSTRAINT AS 
ALTER TABLE PRODUCT MODIFY PRODUCT_NAME VARCHAR2(100) NOT NULL
--CHECKING WHETHER WE CAN DO THAT FOR THE UNIQUE CONSTRAINT AS 
ALTER TABLE PRODUCT MODIFY PRODUCT_NAME VARCHAR2(100) UNIQUE
--DROPPING THE PRIMARY KEY CONSTRAINT AS 
ALTER TABLE PRODUCT DROP CONSTRAINT PK_PRODUCT
--CHECKING FOR THE PRIMARY KEY AS TO MODIFY 
ALTER TABLE PRODUCT MODIFY PRODUCT_ID NUMBER PRIMARY KEY
--DROPPING THE FOREIGN KEY CONSTRAINT AS 
ALTER TABLE PRODUCT DROP CONSTRAINT FK_TORE_ID
--WE CAN ADD THE FOREIGN KEY CONSTRAINT AS BELOW 
ALTER TABLE PRODUCT ADD CONSTRAINT FK_STORE FOREIGN KEY (STORE_ID) REFERENCES STORE(STORE_ID)
--DROPING THE CONSTRINT 
ALTER TABLE PRODUCT DROP CONSTRAINT FK_STRID
--NOW TRYING THE SAME FOR THE FOREIGN KEY FIELD AS BELOW WHICH IS NOT POSSIBLE 
ALTER TABLE PRODUCT MODIFY STORE_ID NUMBER FOREIGN KEY (STORE_ID) REFERENCES STORE(STORE_ID)
-- HERE WE CAN CHECK FOR THE CHECK CONSTRAINT AS WELL 
ALTER TABLE PRODUCT MODIFY PRODUCT_NAME VARCHAR2(100) CHECK (PRODUCT_NAME=UPPER(PRODUCT_NAME))



DESCRIBE STORE

--WE CAN ALSO USE ALTER TO CHANGE THE NAME OF THE FIELD AS WELL
ALTER TABLE STORE RENAME COLUMN CITY TO CITY_NAME 

--TO ADD AN ADDITIONAL COLUMN WE CAN USE AS 
DESCRIBE PACS_GRADE

--WE CAN USE THE ADD OPTION WITH ALTER AS TO ADD A NEW COLUMN BUT WITH NULL VALUE 
ALTER TABLE PACS_GRADE ADD CHECKING VARCHAR2(50)

--DROPING THE COLUMN AS BELOW , HERE THE DATA TYPE NOT REQUIRED
ALTER TABLE PACS_GRADE DROP COLUMN CHECKING 

--WE CAN ALSO ADD THE DEFAULT CONSTRAINT AS BELOW WHICH WILL TAKE THE DEFAULT VALUE AS 
ALTER TABLE PACS_GRADE ADD CHECKING VARCHAR2(50) DEFAULT 'ALL_OK'

--NOW IF WE ARE CHECKING THE DATA THEN
SELECT * FROM PACS_GRADE

--WE CAN ALSO CHANGE THE TABLE NAME AS 
ALTER TABLE PACS_GRADE
RENAME TO PACS_GRADE_NEW



