--CHECKING ALL THE AVAILABLE CONSTRAINT AS 
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME='PACS'
--ALTERING THE CONTENT OF THE TABLE 
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME='PACS'
--CHECKING THE TABLE STRUCTURE OF PACS
DESCRIBE PACS
--ALTERUNG THE NOT NULL CONSTRAINT
ALTER TABLE PACS MODIFY SCHEME NUMBER NOT NULL 
--ALSO BY USING THIS WE CAN ALSO CHANGE THE TYPE OF COLUMN
ALTER TABLE PACS MODIFY A1141CODE VARCHAR2(50)
--HERE ALSO WE CAN PROVIDE THE SAME COMMAND TO CHANGHE THE COLUMN NAME
ALTER TABLE PACS RENAME COLUMN A1141CODE TO A1141CODENEW
--ADDING  A NEW COLUMN TO THE EXISTING TABLE AS 
ALTER TABLE PACS ADD SERVICE_PACS VARCHAR2(50) 
--DROPING THE NEW COLUMN FROM THE TABLE
ALTER TABLE PACS DROP COLUMN SERVICE_PACS 
--NOW ADDING THE TABLE WITH THE HELP OF DEFAULT CONSTRAINT
ALTER TABLE PACS ADD SERVICE_PACS VARCHAR2(50) DEFAULT 'ALL_OK'
--ADDING A NEW CONSTRAINT 
ALTER TABLE PACS ADD CONSTRAINT UN_SCHEME UNIQUE(SCHEME)
--DISABLE CONSTRAINT
ALTER TABLE PACS DISABLE CONSTRAINT UN_SCHEME
--ENABLE CONSTRAINT
ALTER TABLE PACS ENABLE CONSTRAINT UN_SCHEME

