--CASE STATEMENT EXAMPLE
--EXAMPLE:-1
SELECT E.*,
CASE 
WHEN E.SAL>=0 AND E.SAL<=1000 THEN 'A'
WHEN E.SAL>=1000 AND E.SAL<=2000 THEN 'B' 
WHEN E.SAL>=2000 AND E.SAL<=3000 THEN 'C' 
WHEN E.SAL>=3000 AND E.SAL<=4000 THEN 'D' 
WHEN E.SAL>=4000 AND E.SAL<=5000 THEN 'E'
ELSE 'OTHER'
END AS "SALARY_GRADE"
FROM EMP E     

--EXAMPLE:-2
--BASED ON THE JOB PROVIDING THE RESPONSE

SELECT E.*,
 CASE
 WHEN E.JOB='PRESIDENT' THEN 'BIG SHOT'
 WHEN E.JOB='MANAGER' THEN 'HO HO MANAGER'
 ELSE 'DOES NOT MATTER'
 END AS "MESSAGE"
 FROM EMP E 

