--USING THE CTAS COMMAND TO CREATE THE TABLE
CREATE TABLE DEST_TBL1 AS SELECT * FROM EMP
--HERE WE ARE GOING TO DELETE ALL THE DATA AND FEED THAT BY INSERT ALL WITH MULTI TABLE COMMAND 
SELECT D1.* FROM DEST_TBL1 D1
--DELETING THE DATA BY USING THE DELETE COMMAND
DELETE FROM DEST_TBL1
--HERE ALSO WE WILL BE USING THE SAME FOR DEST_TBL2 THE SAME  
CREATE TABLE DEST_TBL2 AS SELECT * FROM EMP
--HERE WE ARE GOING TO DELETE ALL THE DATA AND FEED THAT BY INSERT ALL WITH MULTI TABLE COMMAND 
SELECT D2.* FROM DEST_TBL2 D2
--DELETING THE DATA BY USING THE DELETE COMMAND
DELETE FROM DEST_TBL2
--SELECTING FROM THE EMP
SELECT * FROM EMP
--NOW WE CAN USE THE INSERT ALL COMMAND TO INSERT DATA INTO DEST_TBL1 AND DEST_TBL2 FROM THE SOURCE TABLE EMP USING THE INSERT ALL COMMAND AS 
INSERT ALL
INTO DEST_TBL1 (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
VALUES (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
INTO DEST_TBL2 (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
VALUES (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
SELECT E.* FROM EMP E
WHERE E.EMPNO IN (7839,7698,7782,7566)
--NOW CHECKING THE DEST_TBL1 AND DEST_TBL2 AS BELOW
SELECT D1.* FROM DEST_TBL1 D1
SELECT D2.* FROM DEST_TBL2 D2
--WE CAN SEE THE STRUCTURE OF THE TABLE AS 
DESCRIBE DEST_TBL1

--CREATING THE DEST TABLE 3 FOR THE BELOW CASE
CREATE TABLE DEST_TBL3 AS SELECT * FROM EMP
--DELETING THE ELEMENT AS 
DELETE FROM DEST_TBL3
--USING THE INSERT_ALL WITH CONDITION ALONG WITH SOURCE TABLE 
INSERT ALL 
WHEN SAL < 1500 THEN
INTO DEST_TBL1 (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
VALUES (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
WHEN SAL BETWEEN 1500 AND 3000 THEN
INTO DEST_TBL2 (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
VALUES (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
WHEN SAL>3000 THEN
INTO DEST_TBL3 (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
VALUES (EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO)
SELECT * FROM EMP