--USING THE NATURAL JOIN
SELECT * FROM EMP  NATURAL JOIN DEPT
--USING THE USING CLAUSE
SELECT * FROM EMP JOIN DEPT USING (DEPTNO)
--USING THE COR-RELATED SUBQUERY 
SELECT * FROM EMP
WHERE EXISTS(SELECT 'RANDOM' FROM DUAL)
--ANOTHER EXAMPLE
SELECT D.* FROM DEPT D 
WHERE EXISTS(SELECT E.* FROM EMP E WHERE E.DEPTNO=D.DEPTNO )



--CREATING THE VIEW AS 
CREATE VIEW EMP_VIEW AS SELECT * FROM EMP
--USING THE SELECT THE 
SELECT * FROM EMP_VIEW
--USING THE VIEW FOR PACS_GRADE TABLE AS 
CREATE VIEW PACS_VIEW AS SELECT * FROM PACS_GRADE_NEW
--USING THE VIEW FOR THE INSERT OPERATION
INSERT INTO PACS_VIEW(GRADE_LEVEL,LOWER_SAL,HIGHER_SAL) VALUES ('F',5001,6000)
--FETCHING THE VALUE AS
SELECT * FROM PACS_VIEW



--CHECKING THE CASE STATEMENT 
SELECT E.*, 
(CASE
WHEN E.SAL BETWEEN 1500 AND 3000 THEN 'BIG SHORT'
ELSE 'DOES NOT MATTER' 
END) AS "CASE_INFO"
FROM EMP E
--EQUI JOIN STATEMENT IN ORACLE SQL
SELECT E.*,D.*
FROM EMP E, DEPT D
WHERE E.DEPTNO=D.DEPTNO

