--EQUIJOIN STATEMENT 
SELECT E.*,D.*FROM EMP E , DEPT D
WHERE E.DEPTNO=D.DEPTNO

--CREATING THE TABLE FOR MENTIONING THE NONEQUI JOIN

CREATE TABLE PACS_GRADE(
    GRADE_LEVEL VARCHAR2(20) NOT NULL,
    LOWER_SAL NUMBER NOT NULL,
    HIGHER_SAL NUMBER NOT NULL
)

INSERT ALL 
INTO PACS_GRADE 
VALUES ('A',0,1000)
INTO PACS_GRADE
VALUES ('B',1001,2000)
INTO PACS_GRADE
VALUES ('C',2001,3000)
INTO PACS_GRADE
VALUES ('D',3001,4000)
INTO PACS_GRADE
VALUES ('E',4001,5000)
SELECT * FROM DUAL

--FETCHING THE VALUE AS 
SELECT * FROM PACS_GRADE 

--USING THE NON EQUIJOIN FOR THIS 
--AS WE DON'T HAVE THE DEPT NO THAT WE CAN PROVIDE EQUIJOIN
--BUT WE CAN PERFORM THE NON EQUI JOIN IN THAT CASE

SELECT E.*,P.GRADE_LEVEL FROM EMP E,PACS_GRADE P
WHERE E.SAL<P.HIGHER_SAL AND E.SAL>P.LOWER_SAL

--ALTERNATE WE CAN ALSO USE THE BETWEEN CLAUSE FOR THIS 

SELECT E.*,P.GRADE_LEVEL FROM EMP E,PACS_GRADE P
WHERE E.SAL BETWEEN P.LOWER_SAL AND P.HIGHER_SAL

--WE CAN ALSO USE THE JOIN OVER HERE BUT NOT WITH EQUALITY RATHER WE CAN PUT THE > AND < SYMBOL OR CAN USE BETWEEN AS BELOW 

SELECT E.* ,P.GRADE_LEVEL
FROM EMP E JOIN PACS_GRADE P
ON  E.SAL BETWEEN P.LOWER_SAL AND P.HIGHER_SAL

--WE CAN ALSO USE THE > AND < SYMBOL AS BELOW 

SELECT E.* ,P.GRADE_LEVEL
FROM EMP E JOIN PACS_GRADE P
ON  E.SAL>=P.LOWER_SAL AND E.SAL<=P.HIGHER_SAL



