--EXISTS KEYWORD WITH THE SUBQUERY  IN THE WHERE CLAUSE
--USING IT IN THE DUAL TABLE 
SELECT 'HELLO' FROM DUAL WHERE EXISTS (SELECT * FROM DUAL)
--OTHER USE CASE OF EXISTS WITH THE SUBQUERY IN THE WHERE CLAUSE AS BELOW 
SELECT E.* FROM EMP E WHERE EXISTS(SELECT * FROM DUAL )
--USING THE FALSE CONDITION HERE USING THE NOT EXISTS WITH SUBQUERY IN THE WHERE CLAUSE
SELECT E.* FROM EMP E WHERE NOT EXISTS(SELECT * FROM DUAL )


--CORELATED SUBQUERY IN ORACLE SQL 
--USING THE CORELATED SUBQUERY WITH THE EXISTS IN WEHERE CLAUSE AND USING THE OUTER VARAIBLE REFERENCE INSIDE SUBQUERY REFERENCE TO FETCH THE VALUE 
SELECT D.* FROM DEPT D
WHERE EXISTS(SELECT E.* FROM EMP E WHERE D.DEPTNO=E.DEPTNO)

--IF WE WANT TO SEE THE INFO OF THE DEPT WHICH DOES  NOT THERE IN EMP TABLE THEN WE HAVE TO USE THE NOT EXISTS COMMAND AS BELOW 
SELECT D.* FROM DEPT D
WHERE NOT EXISTS(SELECT E.* FROM EMP E WHERE D.DEPTNO=E.DEPTNO)


--CO-RELATED SUBQUERY IS USING THE OUTER VARIABLE QUERY INSIDE THE INNER QUERY 
-- HERE WE ARE ASSOCIATING ALL THE OUTER QUERY WITH THE INNER QUERY USING THE OUTER QUERY REFERENCE 

--THE OTHER AROUND IS POSSIBLE OR NOT CHECKING THAT 
--USING THE INNER QUERY IN THE OUTSIDE QUERY WHETHER THATS POSSIBLE OR NOT 
--WE CAN'T REFERENCE THE INSIDE SUBQUERY VARIABLE IN THE OUTSIDE OF THAT 

--ALONG WITH THE CO-RELATED SUBQUERY WE CAN USE THE AND AND OR QUERY 




