--RELATED JOIN WITH SUB QUERY INFO 
SELECT E.* ,D.* FROM 
(SELECT * FROM EMP WHERE JOB='MANAGER') E ,(SELECT * FROM DEPT WHERE DEPTNO=20) D
WHERE E.DEPTNO=D.DEPTNO

--HERE WE ARE USING THE WHERE CLAUSE IN BOTH THE SUBQUERY IN THE FORM STATEMENT TO FETCH THE VALUE 
SELECT E.* ,D.* FROM 
(SELECT * FROM EMP WHERE JOB IN ('MANAGER','CLERK')) E ,(SELECT * FROM DEPT WHERE LOC='DALLAS') D
WHERE E.DEPTNO=D.DEPTNO

--USGAE OF THE INNER AND OUTER JOIN
SELECT E.*,D.* 
FROM EMP E RIGHT JOIN DEPT D
ON E.DEPTNO=D.DEPTNO

--IF WE CHANGE THE ORDER THEN IT WILL BEHAVE AS RIGHT JOIN INSTEAD OF LEFT JOIN 
--HENCE THE ORDER OF THE TABLE DOES MAYTTER IN THIS CASE
SELECT E.*,D.* 
FROM  DEPT D LEFT JOIN EMP E
ON E.DEPTNO=D.DEPTNO

--HOW TO USE THE OUTER JOIN OPERATOR (+) AS 

SELECT E.*,D.*
FROM EMP E ,DEPT D
WHERE E.DEPTNO=D.DEPTNO(+)

--RELATED JOIN WITH SUB QUERY INFO 
SELECT E.* ,D.* FROM 
(SELECT * FROM EMP WHERE JOB='MANAGER') E ,(SELECT * FROM DEPT WHERE DEPTNO=20) D
WHERE E.DEPTNO=D.DEPTNO

--HERE WE ARE USING THE WHERE CLAUSE IN BOTH THE SUBQUERY IN THE FORM STATEMENT TO FETCH THE VALUE 
SELECT E.* ,D.* FROM 
(SELECT * FROM EMP WHERE JOB IN ('MANAGER','CLERK')) E ,(SELECT * FROM DEPT WHERE LOC='DALLAS') D
WHERE E.DEPTNO=D.DEPTNO

--HOW TO USE THE OUTER JOIN OPERATOR (+) AS 
-- HERE IN THIS CASE EVEN THOUGH THE (+) ON THE RIGHT BUT LEFT OUTER JOIN WILL GOING TO HAPPEN 
SELECT E.*,D.*
FROM EMP E ,DEPT D
WHERE E.DEPTNO=D.DEPTNO(+)

--SIMILARLY IF WE PUT(+) ON THE LEFT HAND SIDE THE RIGHT OUTER JOIN WILL GOING TO HAPPEN IN THIS CASE

SELECT E.*,D.*
FROM EMP E ,DEPT D
WHERE E.DEPTNO(+)=D.DEPTNO

--USAGE OF THE FULL OUTER JOIN WHICH WILL DISPLAY ALL THE FIELD OF THE LEFT ANFD RIGHT TABLE WE DEFINED

SELECT E.*,D.*
FROM EMP E FULL OUTER JOIN DEPT D
ON E.DEPTNO=D.DEPTNO

--WE CAN USE THE NESTED QUERIES IN THE FROM BLOCK  ALONGSIDE THE INNER AND OUTER JOIN QUERIES


SELECT E.*,D.*
FROM (SELECT * FROM EMP) E FULL OUTER JOIN (SELECT * FROM DEPT) D
ON E.DEPTNO=D.DEPTNO


--WHEN WE USE THE SUB QUERY PERFOMANCE WILL BE DEGRADED BUT IT PROVIDE US OPPERTUNITY TO FILTER OUT THE RESULT 

SELECT E.*,D.*
FROM (SELECT * FROM EMP WHERE JOB IN ('MANAGER','CLERK')) E FULL OUTER JOIN (SELECT * FROM DEPT WHERE DEPTNO IN (10,20)) D
ON E.DEPTNO=D.DEPTNO

--IF WE ARE USING THE  SUB QUERY WITH CONDITION BASED ON THE JOIN IT WILL PROVIDE DIFFERENT OUTPUT 
-- IF INNER JOIN ONLY DISPLAY THE CONDITION MATCHED ROW 
-- IF LEFT/RIGHT JOIN DISPLAY THE CONDITION MATCHED FOR THE SPECIFIC ROW REST WILL BE NULL
-- IF ITS A FULL JOIN IN THAT CASE BOTH THE CASE NULL VALUE WILL COME IF CONDITION NOT MATCHED AND CONDITION MATCHED WILL BE DISPLAYED THE VALUE 

--USING THE RIGHT OUTER JOIN
SELECT E.*,D.* 
FROM (SELECT * FROM EMP WHERE JOB='SALESMAN') E RIGHT OUTER JOIN (SELECT * FROM DEPT) D
ON E.DEPTNO=D.DEPTNO

--USING THE FULL OUTER JOIN 

SELECT E.*,D.* 
FROM (SELECT * FROM EMP WHERE JOB='SALESMAN') E FULL OUTER JOIN (SELECT * FROM DEPT) D
ON E.DEPTNO=D.DEPTNO

--IF WE CHANGE THE ORADER OF THE TABLE AND DO THE LEFT OUER JOIN THE RESULT WILL BE AS
--HERE ALSO THE ORDER OF THE TABLE WILL COME INTO THE CONSIDERATION

SELECT E.*,D.* 
FROM (SELECT * FROM DEPT) D LEFT OUTER JOIN (SELECT * FROM EMP WHERE JOB='SALESMAN') E 
ON E.DEPTNO=D.DEPTNO



