--SELF JOIN IN THIS CASE
SELECT * FROM EMP
--USING THE SELF JOIN WITH OUT THE JOIN STATEMENT 
SELECT E.ENAME,M.ENAME FROM EMP E ,EMP M
WHERE E.MGR=M.EMPNO
--USING THE SELF JOIN WITH THE INNER JOIN KEYWORD 
SELECT E.ENAME,M.ENAME FROM EMP E INNER JOIN EMP M
ON E.MGR=M.EMPNO
--USING THE LEFT JOIN TO DISPLAY THE MGR COLUMN VALUE WHEN ITS NULL 
SELECT E.ENAME,M.ENAME FROM EMP E LEFT JOIN EMP M
ON E.MGR=M.EMPNO

--CROSS JOIN AND NATURAL JOIN IN THE SQL 
--EVERY SINGLE ROW OF ONE TABLE RELATED TO THE ALL THE ROW OF THE OTHER TABLE 
--HERE CARTISIAN PRODUCT WILL GOING TO COME IN THE OUTPUT
SELECT E.*,D.* FROM EMP E,DEPT D

--WE CAN ALSO DO THE SAME USING THE CROSS JOIN AS BELOW 
--CROSS JOIN ALSO CONSIDER AS NO JOIN
SELECT E.*,D.* FROM EMP E CROSS JOIN DEPT D

-- IN CASE OF NATURAL JOIN DOES NOT HAVE TO PROVIDE CONDITION AND IT WILL AUTOMATICALLY RELATE THE CORELATED COLUMN
--IN CASE OF THE NATURAL JOIN WE CAN'T USE VARIABLE OR ALIASES
SELECT ENAME ,LOC FROM EMP NATURAL JOIN DEPT

--USING CONCEPT WHILE JOINING THE TABLE
--INNER JOIN CAN ALSO BE CONSIDERED AS JOIN ONLY
--INSTEAD OF ON WE CAN ALSO USE THE USING INORDER TO PROVIDE RELATIONSHIP
--HERE IN USING WE JUST HAVE TO PROVIDE THE COMMON FIELD NAME 
--HERE WE CAN USE THE ALIASES AS WELL
--IF THE COULMN NAME BEING DIFFERENT THEN WE HAVE TO USE BOTH THE NAME IN THE USING BLOCK AS (COL1,COL2)
--HERE AS ITS SAME WE DON'T HAVE TO DO THAT 

SELECT E.ENAME,D.LOC FROM EMP E JOIN DEPT D USING (DEPTNO)

--WE CAN ALSO USE LEFT/RIGHT JOIN IN THIS CASE

--HERE USING THE LEFT JOIN IN THIS CASE
SELECT E.ENAME,D.LOC FROM EMP E  LEFT JOIN DEPT D USING (DEPTNO)
--USING THE RIGHT JOIN IN THIS CASE
SELECT E.ENAME,D.LOC FROM EMP E  RIGHT JOIN DEPT D USING (DEPTNO)


