--USING THE TO_CHAR() WITH VARCHAR2 INSIDE IT AS
SELECT TO_CHAR(SYSDATE,'DDTH-"OF"-MONTH-YYYY') FROM DUAL D
--USING THE TO_CHAR() TO TURN THE NUMBER INTO THE VARCHAR2() VALUE AS
SELECT TO_CHAR(E.SAL,'$9,999.99') AS "FORMATTED ESAL" FROM EMP E
--USING THE EMP TABLE OVER HERE AS 
SELECT E.*, TO_CHAR(E.SAL,'$9,999.9') AS "FORMATEED_SAL" FROM EMP E


--NVL FUNCTION ARE USED AS SINGLE ROW FUNCTION IN SELECT AND WHERE CLAUSE
--WE CAN CONVERT THE NULL VALUE INTO ZERO BY USING THE NVL FUNCTION FOR THE NUMBER FIELD
-- FOR THE STRING FIELD WE CAN PROVIDE STRING AS DEFAULT VALUE 
--BUT IF WE HAVE TO PROVIDE STRING AS DEFAULT VALUE FOR NUMBER FIELD IF ITS EMPTY THEN DIRECTLY ITS NOT POSSIBLE 
-- WE HAVE TO CONVER THE NUMBER FIELD INTO VARCHAR2 FIELD AND THEN USE  THE NVL FUNCTION WITH DEFAULT STRING VALUE  
SELECT E.*,NVL(TO_CHAR(E.COMM),'NO DATA FOUND') AS "CHECKING_VALUE" FROM EMP E

--USING THE NVL2 TO CHECK FOR THE STRING FIELD AS BELOW 
--NVL2 PROVIDE US THE FACILITY TO PROVIDE AN ALTERNATE VALUE IF THE FIELD IS NOT NULL 
--THIS IS NOT PROVIDED BY THE NVL FUNCTION NORMALLY
SELECT E.*,NVL2(TO_CHAR(E.COMM),'DATA FOUND','NO DATA FOUND') AS "CHECKING_VALUE" FROM EMP E

--USING THE NULLIF(ARGS1,ARGS2)
--HERE ARGS1 AND ARGS2 WILL BE MATCHED AND RETURN TRUE THEN THE VALUE WILL BE NULL ELSE RETURN THE ARGS1 WHICH BEING COMPARED
SELECT E.*,NULLIF(LENGTH(E.ENAME),5) AS "CHECK_VAL" FROM EMP E 
--PROBLEM STATEMENT 
--USING THE NVL FUNCTION WE HAVE TO PUT THE LENGTH AS 'LENGTH IS 5 WHERE ITS NULL IN THE ABOVE PROBLEM'
SELECT E.*,NVL(TO_CHAR(NULLIF(LENGTH(E.ENAME),5)),'LENGTH IS 5') AS "CHECK_VAL" FROM EMP E  


