--SELECTING ALL THE ELEMENTS
SELECT * FROM EMP;
--HERE WE ARE USING THE BETWEEN CLAUSE HERE
SELECT E.* FROM EMP E WHERE HIREDATE BETWEEN '11/17/1980' AND '05/01/1981'
--PREVEIOUS QUERY WITH THE OR QUERY AS BELOW 
SELECT E.ENAME,E.HIREDATE,D.LOC FROM EMP E INNER JOIN DEPT D ON E.DEPTNO=D.DEPTNO WHERE D.LOC='DALLAS' OR D.LOC='CHICAGO'
--IF THE FIELDS ARE OF SAME THEN INSTEAD OF OR WE CAN USE THE IN CALUSE AS BELOW 
SELECT E.ENAME,E.HIREDATE,D.LOC FROM EMP E INNER JOIN DEPT D ON E.DEPTNO=D.DEPTNO WHERE D.LOC IN ('DALLAS','CHICAGO')
--MUOLTIPLE IN CLAUSE
SELECT E.ENAME,E.HIREDATE,D.LOC FROM EMP E INNER JOIN DEPT D ON E.DEPTNO=D.DEPTNO WHERE D.LOC IN ('DALLAS','CHICAGO') 
AND E.ENAME IN ('SCOTT','FORD','SMITH','ALLEN','WARD') ORDER BY E.ENAME
--HOW TO USE THE NULL COMMAND 
SELECT E.* FROM EMP E WHERE MGR IS NULL
SELECT E.* FROM EMP E WHERE MGR IS NOT NULL
--ADDING A NEW CONSTRAINT TO THE TABLE AS 
SELECT * FROM EQUIPMENT
--INSERTING ELEMENT TO THE TABLE 
INSERT INTO EQUIPMENT E (E.ID,E.CPNUMBER,E.SNEID,E.TRSAREA,E.CREATED) VALUES (1,'CP00XX',224534,'L/WAT','10-9-2022')

--HERE ADDING THE ADDITIONAL CONSTRAINT TO THE TABLE 
ALTER TABLE EQUIPMENT ADD CONSTRAINT SNEID_NOTNULL UNIQUE (SNEID)

--SOLVING PROBLEM 

--FETCHING THE EMP WHOSE COMM SALARY > 1100 AND SALARY < 5000 AND SALARY !=1500
SELECT E.* FROM EMP E WHERE E.COMM IS NULL AND E.SAL > 1100 AND E.SAL < 5000 AND E.SAL<>3000 OR E.COMM=0 
--ALTERNATE SOLUTION
SELECT E.* FROM EMP E WHERE (E.COMM IS NULL OR E.COMM=0) AND (E.SAL > 1100 AND E.SAL < 5000 AND E.SAL<>3000)


--PROBLEM STATEMENT:-2
--INCLUDING THE E.COMM=0 OR E.COMM=NULL AND 1100<E.SAL<5000 AND ESAL != 1500
SELECT E.* FROM EMP E WHERE E.COMM IS NULL AND (E.SAL > 1100 AND E.SAL < 5000 AND E.SAL NOT IN (1500)) OR (E.COMM=0 AND E.SAL<>1500)
--ALTERNATE SOLUTION
SELECT E.* FROM EMP E WHERE (E.COMM IS NULL OR E.COMM=0) AND (E.SAL>1100 AND E.SAL<5000 AND E.SAL<>1500)  

--ANOTHER CHECK
--HERE FETCHING EMPLOYEE WHOSE COMMISION IS NULL AND SALARY >1100 AND  SALARY <5000 
SELECT E.* FROM EMP E WHERE E.COMM IS NULL AND E.SAL<>1500 AND (E.SAL>1100 AND E.SAL<5000) 