--SUBQUERIES IN ORACLE SQL 
--THIS WILL HELP IN FETCH THE 2ND HIGHEST SALARY IN THE TABLE 

SELECT MAX(E.SAL) FROM EMP E
WHERE E.SAL<(SELECT MAX(E1.SAL) FROM EMP E1)

-- WE CAN ALSO USE THE DIFFERENT TABLE IN THE SUBQUERY AS BELOW 

SELECT E.* FROM EMP E
WHERE E.DEPTNO=(SELECT D.DEPTNO FROM DEPT D WHERE D.DEPTNO=10)

--USING THE SUBQUERIES INSIDE THE FROM STATEMENT AS WELL AS BELOW 

SELECT ENAME,DEPTNO FROM 
(SELECT E1.ENAME,E1.DEPTNO FROM EMP E1 WHERE E1.DEPTNO=20 )

--USING THE MULTIPLE TABLE IN THE SUBQUERY 

SELECT E.* FROM EMP E
WHERE E.DEPTNO=(SELECT D.DEPTNO FROM DEPT D WHERE D.LOC='DALLAS')

--USING THE DUBQUERY IN THE SELECT PHASE AS WELL 

SELECT E.*,(SELECT D.DNAME FROM DEPT D WHERE D.DEPTNO=E.DEPTNO) AS "DEPT INFO",
(SELECT D.LOC FROM DEPT D WHERE D.DEPTNO=E.DEPTNO) AS "LOCATION INFO"
FROM EMP E

--HANDLING MULTIPLE OUTPUT FOR THE WEHERE CLAUSE USING THE IN OPERATOR IN THE WHERE CLAUSE 

SELECT E.* FROM EMP E 
WHERE E.DEPTNO IN (SELECT D.DEPTNO FROM DEPT D)

--USING THE IN OPERATOR IN THE SELECT STATEMENT AS BELOW (WHICH IS NOT POSSIBLE)

SELECT E.*,(SELECT E1.ENAME FROM EMP E1  WHERE E1.DEPTNO=(SELECT D.DEPTNO FROM DEPT D WHERE D.LOC='CHICAGO') AND E1.JOB='MANAGER') AS "MANAGER_WHO_BELONG_TO_DEPT_30"
FROM EMP E WHERE E.JOB='MANAGER'


--WE CAN ALSO USE THE SUBQUERY AS 
SELECT 'HELLO' FROM DUAL

--HERE WE CAN UTILIZE THAT AS BELOW 

SELECT E.*,(SELECT 'HELLO' FROM DUAL) AS MSG
FROM EMP E
